
backend:
  image: pdonorio/py3apil
  environment:
    # - UWSGI_EMPEROR=/etc/uwsgi/emperor.ini
    - UWSGI_MASTER=/tmp/uwsgi/starter.ini
    - NGINX_ACTIVE=true
  hostname: restapi
  volumes:
    # - ./wsgi:/etc/uwsgi
    - ./wsgi:/tmp/uwsgi
    - nginx_empty_sites:/etc/nginx/sites-enabled
    - ./nginx_internal:/etc/nginx/conf.d
    - ./app:/code

# proxy:
#   image: nginx
#   hostname: iamaproxy
#   links:
#     - backend:api
#   volumes:
#     - ./nginx_proxy:/etc/nginx/conf.d
#   ports:
#     - 80:80

client:
  image: eudatb2safe/apiclient
  hostname: flaskclient
  command: sleep 1234567890
  links:
    - backend:api
    # - proxy:proxy
