
backend:
  image: pdonorio/py3apil
  # command: sleep infinity
  command: uwsgi --emperor /etc/uwsgi/emperor.ini
  hostname: restapi
  volumes:
    - ./app:/code
    - ./etc:/etc/uwsgi
    # - pocs_virtualenv:/srv
  ports:
    - 3031:3031

client:
  image: eudatb2safe/apiclient
  command: sleep 1234567890
  links:
    - backend:api

# proxy:
#   image: nginx
#   links:
#     - backend:api
#   ports:
#     - 80:80
