version: "2.0"

services:

  dbr:
    image: rethinkdb
    networks:
      - internal_poc
    volumes:
        - rethinkdbdata:/data
  hub:
    image: nb
    networks:
      - internal_poc
    depends_on:
      - dbr
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/data
    working_dir: /data

volumes:
  rethinkdbdata:
    driver: local

networks:
  internal_poc:
    driver: bridge
